---
- name: Deploy Dozzle in Docker Container using Docker Compose
  hosts: homelab
  become: yes
  tasks:
    - name: Create directory for Dozzle's docker-compose.yml
      become: yes
      ansible.builtin.file:
        path: /opt/docker/dozzle
        state: directory
        mode: '0755'

    - name: Create docker-compose.yml for Dozzle
      become: yes
      ansible.builtin.copy:
        dest: /opt/docker/dozzle/docker-compose.yml
        content: |
          version: '3'
          services:
            dozzle:
              image: amir20/dozzle:latest
              ports:
                - "8888:8080"
              environment:
                - DOZZLE_LEVEL=info
              volumes:
                - "/var/run/docker.sock:/var/run/docker.sock"
