---
- name: dockcheck
  hosts: homelab
  tasks:
    - name: Navigate to /opt/docker/dockcheck
      command: cd /opt/docker/dockcheck
      register: cd_result
      failed_when: cd_result.rc != 0
      changed_when: false

    - name: Check for updates using dockcheck
      command: ./dockcheck -n
      register: dockcheck_output
      changed_when: false

    - name: Update and prune if updates are available
      command: ./dockcheck -a -p
      when: "'Updates are available' in dockcheck_output.stdout"