---
- name: Prune Docker Volumes, Networks, and Images
  hosts: "homelab"
  become: yes

  tasks:
    - name: Prune Docker volumes
      community.docker.docker_prune:
        resource: volumes
      register: docker_volume_prune_result

    - name: Prune Docker networks
      community.docker.docker_prune:
        resource: networks
      register: docker_network_prune_result

    - name: Prune Docker images
      community.docker.docker_prune:
        resource: images
      register: docker_image_prune_result

    - name: Display Docker prune results
      debug:
        var: item
      loop:
        - "{{ docker_volume_prune_result }}"
        - "{{ docker_network_prune_result }}"
        - "{{ docker_image_prune_result }}"
