---
- name: Install Ansible Galaxy dependencies
        name: community.docker.docker_prune

- name: docker prune (not containers)
  hosts: "homelab"
  become: yes
    community.docker.docker_prune:
      images: true
      networks: true
      volumes: true