---
- hosts: "homelab"
  become: yes
  
  tasks:
    - name: Install Ansible Galaxy dependencies
      ansible.builtin.pip:
        name: community.docker.docker_prune
        state: present
        tags: semaphore

    - name: docker prune (not containers)
      community.docker.docker_prune:
          images: true
          networks: true
          volumes: true