---
- name: dockcheck
  hosts: homelab
  become: true
  tasks:
    - name: Navigate to /opt/docker/dockcheck
      shell: "navigate to /opt/docker/dockcheck"
        args:
          command: cd /opt/docker/dockcheck

    - name: Check for updates using dockcheck
      command: ./dockcheck.sh -n
      register: dockcheck_output
      changed_when: false

    - name: Update and prune if updates are available
      command: ./dockcheck.sh -a -p
      when: "'Updates are available' in dockcheck_output.stdout"