---
- name: Docker Prune Playbook
  hosts: homelab
  become: yes
  tasks:
    - name: Prune Docker volumes, networks, and images
      community.docker.docker_prune:
        volumes: yes
        networks: yes
        images: yes
        containers: no
        builder_cache: no
      register: prune_result

    - name: Display prune result
      debug:
        var: prune_result
