---
- name: dockcheck
  hosts: homelab
  become: true
  tasks:
    - name: Check for updates using dockcheck
      command: sh /opt/docker/dockcheck/dockcheck.sh -n
      args:
        chdir: /opt/docker/dockcheck
      register: dockcheck_output
      changed_when: false

    - name: Update and prune if updates are available
      command: sh /opt/docker/dockcheck/dockcheck.sh -a -p
      args:
        chdir: /opt/docker/dockcheck
      when: "'Updates are available' in dockcheck_output.stdout"