---
- name: Check Disk Space on Ubuntu
  hosts: homelab
  become: yes
  tasks:
    - name: Check disk space
      shell: df -h
      register: disk_space

    - name: Display disk space
      debug:
        var: disk_space.stdout_lines

    - name: Check if any partition is over 80% full
      shell: df --output=pcent | grep -v Use% | awk '{gsub("%",""); print $1}' | awk '$1 >= 80'
      register: over_80

    - name: Display warning if any partition is over 80% full
      debug:
        msg: "Warning: Some partitions are over 80% full."
      when: over_80.stdout
