---
- name: Update NVIDIA Graphics Card Driver
  hosts: pc   # Replace with the name of the host where you want to update the driver.
  gather_facts: false       # Set to false as we don't need facts for this task.

  tasks:
    - name: Copy PowerShell script
      copy:
        src: https://git.techbybrett.com/brett/powershell-scripts/src/branch/master/nvidia.ps1   # Replace with the actual path to your PowerShell script.
        dest: C:\temp\nvidia.ps1 # Destination path on the remote machine.

    - name: Execute PowerShell script
      win_shell: |
        Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
        C:\temp\update_nvidia.ps1   # Replace with the correct path on the remote machine.

      # If your PowerShell script requires elevated privileges, you may use the following instead:
      # become: yes
      # become_method: runas
      # args:
      #   executable: powershell.exe
      #   creates_path: C:\path\to\check\if\already\updated.txt

      register: script_result

    - name: Display script output
      debug:
        var: script_result.stdout_lines