---
- name: Install pip and Docker SDK for Python
  hosts: homelab
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install pip for Python 2
      apt:
        name: python-pip
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present
        executable: pip