---
- name: Install QEMU Guest Agent on Ubuntu
  hosts: homelab
  become: yes
  tasks:
    - name: Update apt repository cache
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Ensure qemu-guest-agent is started and enabled at boot
      service:
        name: qemu-guest-agent
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
