---
- name: Execute backup.sh on Ubuntu VMs
  hosts: homelab
  become: yes 
  tasks:
    - name: Run remote bash script
      command:
        cmd: /opt/docker/backup.sh
      register: script_output

    - name: Display script output
      debug:
        msg: "{{ script_output.stdout }}"
