---
- name: Execute remote bash script on Ubuntu VMs
  hosts: homelab
  become: true
  tasks:
    - name: Run remote bash script with folder name based on hostname
      shell: ./backup.sh {{ inventory_hostname }}
      args:
        chdir: /opt
      register: script_output

    - name: Display script output
      debug:
        msg: "{{ script_output.stdout }}"