---
- name: Execute remote bash script on Ubuntu VMs
  hosts: homelab
  become: yes
  tasks:
    - name: Run remote bash script with folder name based on hostname
      command:
        cmd: "/opt/backup.sh {{ inventory_hostname }}"
      register: script_output

    - name: Display script output
      debug:
        msg: "{{ script_output.stdout }}"