---
- name: Install Watchtower Docker container
  hosts: "host"  
  become: true

  tasks:
    - name: Run Watchtower container
      docker_container:
        name: watchtower
        image: containrrr/watchtower
        restart_policy: unless-stopped
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        command: --cleanup --interval 30  # Adjust the interval as needed
        state: started