---
- name: Deploy Watchtower Docker Container
  hosts: "{{ hosts }}"
  become: yes
  tasks:
    - name: Ensure docker is installed
      apt:
        name: docker.io
        state: present

    - name: Ensure Watchtower container is running
      docker_container:
        name: watchtower
        image: containrrr/watchtower
        state: started
        restart_policy: always
        detach: true
