---
- name: Deploy Watchtower Container
  hosts: "host"
  become: yes

  tasks:
    - name: Ensure Docker Compose is installed
      apt:
        name: docker-compose
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Pull the latest Watchtower image
      docker_image:
        name: watchtower
        source: pull
      register: watchtower_image

    - name: Create Watchtower container
      docker_container:
        name: watchtower
        image: "{{ watchtower_image.image }}"
        state: started
        restart_policy: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        env:
          - WATCHTOWER_CLEANUP=true
          - WATCHTOWER_SCHEDULE= "0 0 4 * * *"