- name: Create watchtower container
  hosts: Home
  become: 'yes'
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower
    pull: true
    state: started
    restart_policy: unless-stopped
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    env:
      WATCHTOWER_CLEANUP: 'true'