---
- name: Build Watchtower Docker container
  hosts: "host"  
  become: true

  tasks:

    - name: Build Watchtower Docker container
      docker_image:
        name: containrrr/watchtower
        tag: latest
        source: build
        build:
          path: /opt/docker/watchtower
      register: docker_build_result

    - name: Print build result
      debug:
        var: docker_build_result